import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";

const getInter = Inter({
  variable: "--font-inter",
});

const getBebas = Bebas_Neue({
  variable: "--bebas-neue",
  weight: '400'
});

export const metadata: Metadata = {
  title: "Astrid Delaney",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getBebas.variable} ${getInter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
